### ISSUE TITLE
Add unit tests for writing to S3 stores

### ISSUE THREAD

**Issue by pont-us** [bcdev/nc2zarr#45]
At present, there are only a couple of very trivial unit tests for S3 access (checking behaviour with invalid parameters). We should add more thorough tests for writing to S3 stores, probably using the [moto library](https://github.com/spulec/moto) for mocks.

**Comment by forman** [comment]
Instead of adding new unit tests, I'd prefer we get rid of any s3-specific code. We can do this by relying entirely on the `fsspec` package and auto-configuration through keyword injection from config YAML. Finally we have less code and need to test.

@pont-us I'd therefore like to add the "wontfix" label and close this one in favor of #46.

**Comment by pont-us** [comment]
> @pont-us I'd therefore like to add the "wontfix" label and close this one in favor of #46.

Agreed and done.
